### ISSUE TITLE
Workflow exceptions might not be caught after WFS 2.x upgrade?

### ISSUE THREAD

**Issue by darrenleeweber** [sul-dlss/sdr-preservation-core#50]
After https://github.com/sul-dlss/sdr-preservation-core/pull/49, review the SDR-PC code for exception handling when issuing WFS calls.  If the exception handling is always catching `StandardError`, it _might_ be OK.

**Comment by jmartin-sul** [comment]
seems ok based on a quick search for `rescue`?

https://github.com/sul-dlss/sdr-preservation-core/search?utf8=%E2%9C%93&q=rescue&type=

**Comment by jmartin-sul** [comment]
from the dor-workflow-service release notes:

* https://github.com/sul-dlss/dor-workflow-service/releases/tag/v2.0.0 - 
  * Replace all `RestClient` usage with `Faraday` with persistent HTTP connections (#26)
  * Improved the `Dor::WorkflowService` abstraction to include methods that `dor-services` went directly to the HTTP API for (#31)
  * Wrap HTTP and other data exceptions in a generic `Dor::WorkflowException`, instead of exposing the underlying HTTP client errors.

**Comment by darrenleeweber** [comment]
This could be a non-issue; we done some analysis on the code to confirm that most of the exceptions catch `StandardError` and the https://github.com/sul-dlss/dor-workflow-service/blob/master/lib/dor/workflow_exception.rb is a subclass of `RuntimeException` which is a subclass of `StandardError`.  Once the new master branch is deployed and running in production for a month or so, we can submit new issues that arise as necessary.
